---
version: "2.0"
services:
  service-1:
    image: mcianni22/passage:nvenc-tests-ffmpeg-v0.0.16
    expose:
      - port: 80
        as: 80
        to:
          - global: true
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          - size: 16Gi
        gpu:
          units: 1
          attributes:
            cuda: 12.8
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 10000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
